version: '3.10'

services:
  db:
    image: mysql/mysql-server
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'aa123456'
    ports:
      - 3306:3306
    volumes:
      - dbgpt-myql-db:/var/lib/mysql
      - ./docker/examples/my.cnf:/etc/my.cnf
      - ./docker/examples/sqls:/docker-entrypoint-initdb.d
      - ./assets/schema/knowledge_management.sql:/docker-entrypoint-initdb.d/knowledge_management.sql
    restart: unless-stopped
    networks:
      - dbgptnet
  webserver:
    image: ./docker/base
    command: bash start.sh
    environment:
      - LOCAL_DB_HOST=db
      - LOCAL_DB_PASSWORD=aa123456
      - ALLOWLISTED_PLUGINS=db_dashboard
      - LLM_MODEL=chatgpt_proxyllm
      - PROXY_API_KEY=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
      - PROXY_SERVER_URL=https://api.openai.com/v1/chat/completions
      - PYTHONUNBUFFERED=1
    depends_on:
      - db  
    volumes:
      - ./start.sh:/app/start.sh
      - /data:/data
      # Please modify it to your own model directory
      - ./models/text2vec-large-chinese:/app/models/text2vec-large-chinese
      - dbgpt-data:/app/pilot/data
      - dbgpt-message:/app/pilot/message
    env_file:
      - .env
    ports:
      - 5000:5000/tcp
    # webserver may be failed, it must wait all sqls in /docker-entrypoint-initdb.d execute finish.
    restart: unless-stopped
    networks:
      - dbgptnet
    ipc: host
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
volumes:
  dbgpt-myql-db:
  dbgpt-data:
  dbgpt-message:
networks:
  dbgptnet:
    driver: bridge
    name: dbgptnet